### PR TITLE
Produce md5 to test function contents

### LINKED ISSUE #16: check function's contents with pg_tapgen
Hi,

I want to use pg_tapgen to automate checking schemas. A few days ago, we had a function with a slight difference between two environments. I think this could be solved easily (except for C functions obviously) by performing a check on is(md5(prosrc). Would this be interesting ? Should I do this patch and propose a pull request ?

Regards

### PR DESCRIPTION
**Pull request by marco44**
close #16 

As proposed in #16 , this will produce a series of is(md5(prosrc)) for all functions.

### CODE REVIEW

**Comment by marco44** [comment]
Hi,

Any news on this ? Anything I can improve ?

**Comment by theory** [comment]
Did you not see the comment about adding a description, @marco44?

**Comment by marco44** [comment]
No, I still don't see this comment. Where should I find it ?

**Comment by theory** [comment]
WTF? Oh, I have to "submit the review". :-( Done.

**Comment by marco44** [comment]
Correction done

**Pull request merged**
